export { default as base } from './base'
export { default as main } from './main'
export { default as allRoutes } from './allRoutes'
export { default as detailInfoPage } from './detailInfoPage'
export { default as personalCenter } from './personalCenter'
export { default as search } from './search'
export { default as order } from './order'
